<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-VK6INC2" failures="1" tests="1" name="SwagLabsTestCasessTest(failed)" time="8.67" errors="0" timestamp="2024-06-13T13:02:05 IST">
  <testcase classname="test_cases.Payment_Finish_Test" name="Clickonfinishbtntest" time="0.119">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/checkout-complete.html] but found [Price Total]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/checkout-complete.html] but found [Price Total]
at test_cases.Payment_Finish_Test.Clickonfinishbtntest(Payment_Finish_Test.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Clickonfinishbtntest -->
  <testcase classname="test_cases.Payment_Finish_Test" name="Verifyshippinginfotest" time="0.0">
    <ignored/>
  </testcase> <!-- Verifyshippinginfotest -->
  <testcase classname="test_cases.Payment_Finish_Test" name="Verifypricetitaltest" time="0.0">
    <ignored/>
  </testcase> <!-- Verifypricetitaltest -->
  <testcase classname="test_cases.Payment_Finish_Test" name="Verifyoverviewtitletest" time="0.0">
    <ignored/>
  </testcase> <!-- Verifyoverviewtitletest -->
  <testcase classname="test_cases.Payment_Finish_Test" name="Verifypaymentinfotest" time="0.0">
    <ignored/>
  </testcase> <!-- Verifypaymentinfotest -->
  <testcase classname="test_cases.Payment_Finish_Test" name="Verifycancelbtntest" time="0.0">
    <ignored/>
  </testcase> <!-- Verifycancelbtntest -->
</testsuite> <!-- SwagLabsTestCasessTest(failed) -->
